The following methods were declared but never implemented (and indeed never called by anyone else):
libVAMOS.so: undefined reference to `CsICalib::SetCalSi(float, float,
float)'
libVAMOS.so: undefined reference to `CsICalib::ECsIch(double)'
libVAMOS.so: undefined reference to `CsICalib::SetCsIPed(float)'
libVAMOS.so: undefined reference to `CsICalib::CalculateCanalCsI()'
libVAMOS.so: undefined reference to `CsICalib::SimulateEvent()'
libVAMOS.so: undefined reference to `CsICalib::ClearEvent(int)'
libVAMOS.so: undefined reference to `CsICalib::CalculateECsI()'
libVAMOS.so: undefined reference to `CsICalib::SetCalCsI(float, float,
float)'