fix bugs introduced by commit dec86f8
/KVMultiDet/base/KVBase.cpp:256:2: error: #endif without #if
Undefined symbols for architecture x86_64:
  "THtml::MakeAll(bool, char const*, int)", referenced from:
      make_examples() in KVClassFactory_examples.C.o
  "THtml::MakeIndex(char const*)", referenced from:
      make_examples() in KVClassFactory_examples.C.o
  "THtml::THtml()", referenced from:
      make_examples() in KVClassFactory_examples.C.o
  "THtml::~THtml()", referenced from:
      make_examples() in KVClassFactory_examples.C.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libKVMultiDetKVClassFactory_examples.dylib] Error 1
make[1]: *** [KVMultiDet/CMakeFiles/KVMultiDetKVClassFactory_examples.dir/all] Error 2